# Generated by Django 3.2.5 on 2021-07-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200, null=True)),
                ('flat_rent', models.CharField(max_length=10)),
                ('e_meter_id', models.CharField(max_length=25, null=True)),
                ('renter_id', models.CharField(max_length=25, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
