# Generated by Django 3.2.5 on 2021-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210703_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
