# Generated by Django 3.2.5 on 2021-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_flat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
