# Generated by Django 3.2.5 on 2021-09-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('flat_rent', models.IntegerField()),
                ('electric_meter', models.CharField(max_length=30, null=True)),
                ('renter_id', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
