# Generated by Django 3.2.5 on 2021-10-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_alter_flat_status'),
        ('meterReading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='name',
        ),
        migrations.AddField(
            model_name='meterreading',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flats.flat'),
        ),
    ]
